# Generated by Django 3.0.8 on 2020-07-15 19:29

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('societies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='society',
            name='members',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL, verbose_name='Members'),
        ),
    ]
