# Generated by Django 3.0.8 on 2020-07-28 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('societies', '0006_auto_20200728_1257'),
    ]

    operations = [
        migrations.AlterField(
            model_name='society',
            name='name',
            field=models.CharField(max_length=200),
        ),
    ]
